language: php
php:
  - '5.6'

env:
  - DB=MYSQL

before_script:
  - composer self-update || true
  - phpenv rehash
  - phpenv config-rm xdebug.ini || true

  - export PATH=~/.composer/vendor/bin:$PATH
  - composer validate
  - composer install --prefer-dist
#  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
#  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
#  - cd ~/builds/ss
#  - composer install

script:
  - "vendor/bin/phpunit vendor/nomidi/silverstripe-bugherd-hero-tool"
