language: php
php:
  - '5.6'

env:
  - DB=MYSQL CORE_RELEASE=4.1 PHPUNIT_TEST=1

before_script:
  - composer self-update || true
  - composer validate
  - composer require --no-update silverstripe/installer:4.1.x
  - phpenv rehash
  - phpenv config-rm xdebug.ini || true

  - export PATH=~/.composer/vendor/bin:$PATH
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile
#  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
#  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
#  - cd ~/builds/ss
#  - composer install

script:
  - "vendor/bin/phpunit tests"
